### ISSUE TITLE
keepalived-vip containers crashes with error after deploy

### ISSUE THREAD

**Issue by vitalka200** [exocode/helm-charts#6]
Hi,
After deploying hetzner-failover-ip container crashes with the following error
```
F0806 11:55:18.222653       1 controller.go:314] Error getting POD information: timed out waiting to observe own status as Running
goroutine 1 [running]:
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.stacks(0xc4202a0100, 0xc42012e1c0, 0x83, 0xd1)
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:766 +0xcf
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).output(0x1d5bc80, 0xc400000003, 0xc420422a50, 0x1cdb4fa, 0xd, 0x13a, 0x0)
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:717 +0x30f
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.(*loggingT).printf(0x1d5bc80, 0x3, 0x1479b89, 0x21, 0xc4206bdcd8, 0x1, 0x1)
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:655 +0x14b
k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog.Fatalf(0x1479b89, 0x21, 0xc4206bdcd8, 0x1, 0x1)
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.newIPVSController(0xc4202024e0, 0x0, 0x0, 0x1, 0x7ffd7dbb4c5b, 0xd, 0x32, 0x3, 0x6)
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/controller.go:314 +0x229
main.main()
	/home/jck/go/src/k8s.io/contrib/keepalived-vip/main.go:127 +0x468
```
Any clue how to solve this?

Thank you!

**Comment by exocode** [comment]
hm,.. not working at the moment on this repo. May you wanna try an older commit? It worked for me before I merged a commit from a user. https://github.com/exocode/helm-charts/tree/54da84d13eb75e6035dfac4d96ffe086ed5864c5

Maybe @voron has an idea to fix it..

**Comment by voron** [comment]
According to [github](https://github.com/kubernetes/contrib/issues/2520) it looks like RBAC issue

**Comment by vitalka200** [comment]
@voron Great. Thank you. just find a typo 👍
